#!/usr/bin/env perl

use 5.010;
use warnings;
use strict;
use JSON;

my $take_note = sub {
    my ( $note) = @_;
    my $config = '.draft';

    open( my $fh, "<", "$config" ) || die "cant open $config: $!";
    my $json = <$fh>;
    close $fh;
    my $os = decode_json $json;
    my $note = '';

    for( @$note){
        chomp;
        $note .= "$_".'<br>';
    };

    my $push_note = system("echo '$note' | '$os->{copy}'");
    my $draft = system("$os->{xurl}[0]");
    my $close = system("$os->{close}[0]");
    return $push_note;

};

sub note {
    my @n = ();
    while( <> ){ push @n, $_ }
    print 'ok' . "\n" unless $take_note->(\@n );
}

note();
