#!/usr/bin/env perl

use 5.010;
use warnings;
use strict;

use Cwd qw< abs_path >;
use JSON::PP;

my $make_link = sub {
    my $file = shift;
    my $link = "$ENV{HOME}/.drafts";
    my $cwd = abs_path('.');
    $file = $cwd . '/' . "$file";
    symlink( $file, $link );
    return $link;
};
    

my $take_note = sub {
    my $note = shift;
    
    my $config = $make_link->('.draft');
    open( my $fh, "<", "$config" ) || die "cant open $config: $!";
    my $json = <$fh>;
    close $fh;
    my $os = decode_json $json;
    #$note = '';

    for( @$note){
        chomp;
        $note .= "$_".'<br>';
    };

    my $push_note = system("echo '$note' | '$os->{copy}'");
    my $draft = system("$os->{xurl}[0]");
    my $close = system("$os->{close}[0]");
    return $push_note;

};

sub note {
    my @n = ();
    while( <> ){ push @n, $_ }
    print 'ok' . "\n" unless $take_note->(\@n );
}

note();
