#!/usr/bin/env perl

use 5.010;
use warnings;
use strict;
use JSON;

my $take_note = sub {
    my ( $n ) = @_;
    my $c = '.draft';

    open( my $fh, "<", "$c" ) || die "dead while opening";
    my $j = <$fh>;
    close $fh;
    my $os = decode_json $j;
    my $note = '';

    for( @$n ){
        chomp;
        $note .= "$_".'<br>';
    };

    my $push_note = system("echo '$note' | '$os->{copy}'");
    my $draft = system("$os->{xurl}[0]");
    my $close = system("$os->{close}[0]");
    return $push_note;

};

sub note {
    my @n = ();
    while( <> ){ push @n, $_ }
    my $success = $take_note->(\@n );
    say $success;
}

note();
